parser <- this.path::ArgumentParser()
parser$add.argument("-a", "-b", "-c")
parser$add.argument("-W", "-Wall", "--Wall")
parser$add.argument("-getwd", action = "exit", exit = getwd())
parser$parse.args()
# (Rscript(this.path(), args = "-h", intern = FALSE))
# (Rscript(this.path(), args = "-h", intern = TRUE ))
# (Rscript(this.path(), args = "-getwd", intern = FALSE))
# (Rscript(this.path(), args = "-getwd", intern = TRUE ))
